ahoyapi: v2
usage: Cli app for development using ahoy.
commands:
  docker:
    usage: Lists available commands
    imports:
      - .ahoy/docker.ahoy.yml

  scrap:
    usage: Run spiders
    cmd: ahoy docker run scraper scrapy runspider spiders.py

  setup:
    usage: Setup all defaults
    cmd: |
      ahoy docker run defaults python /code/create_defaults.py
      ahoy docker exec geo python /code/manage.py migrate
      ahoy docker exec geo python /code/manage.py preload_citi_polygons

  backup:
    usage: Backups grafana dashboards
    cmd: |
      ahoy docker run defaults python /code/backup_dashboards.py
